/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java1;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabo
 */
public class comboBox extends javax.swing.JFrame {
    DefaultComboBoxModel combo = new DefaultComboBoxModel();
    DefaultComboBoxModel pares = new DefaultComboBoxModel();
    DefaultComboBoxModel impares = new DefaultComboBoxModel();

    /**
     * Creates new form comboBox
     */
    public comboBox() {
        initComponents();
      // llenarCombo();
      llenarCombo2();
    }
    
    public void llenarCombo(){
        
        int [] numeros = {1,2,3,4,5,6,7,8,9,10};
        
        for (int i =1; i <=numeros.length; i++) {
            
            jcbxNumerosDefault.addItem(String.valueOf(i));
            
        }
        
    }
    
    public void llenarCombo2(){
        
         int [] num = {2,4,6,8,10,12};
        
        for (int i = 0; i < num.length; i++) {
            
            combo.addElement(num[i]);
            
        }
        jcbxNumerosDefault.setModel(combo);
    }
    
    
    public void sumarCombo(){
        
        int numCombo;
        int resultado=0;
        for (int i = 0; i <combo.getSize(); i++) {
            
              numCombo = Integer.parseInt(combo.getElementAt(i).toString());
             resultado+=numCombo;
        }
        jtxtResultadoCombo.setText(String.valueOf(resultado));
    }
    
    public void ingresoparesImpares(){
        
        if (Integer.parseInt(jtxtIngresoParesImpares.getText())%2==0) {
            
           pares.addElement(jtxtIngresoParesImpares.getText());
           jcbxComboPares.setModel(pares);
           jtxtIngresoParesImpares.setText("");
            
        } else {
            
            impares.addElement(jtxtIngresoParesImpares.getText());
            jcbxComboImpares.setModel(impares);
            jtxtIngresoParesImpares.setText("");
        }
        
    }
    
    public void sumarParesImpares(){
        
        int numPar;
        int resultadoPar=0;
        int numImpar;
        int resultadoImpar=0;
        
        for (int i = 0; i < pares.getSize(); i++) {
            
            numPar = Integer.parseInt(pares.getElementAt(i).toString());
            resultadoPar+=numPar;
            
        }
        
        for (int i = 0; i < impares.getSize(); i++) {
            
            numImpar = Integer.parseInt(impares.getElementAt(i).toString());
            resultadoImpar+=numImpar;
            
        }
        
        JOptionPane.showMessageDialog(null, "RESULTADO PARES : "+resultadoPar+"\n"+"RESULTADO IMPARES: "+resultadoImpar);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbxNumerosDefault = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jtxtResultadoCombo = new javax.swing.JTextField();
        jcbxComboPares = new javax.swing.JComboBox<>();
        jtxtIngresoParesImpares = new javax.swing.JTextField();
        jbtnIngreso = new javax.swing.JButton();
        jcbxComboImpares = new javax.swing.JComboBox<>();
        jbtnResultadoParesImpares = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("SUMA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jbtnIngreso.setText("INGRESO");
        jbtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresoActionPerformed(evt);
            }
        });

        jcbxComboImpares.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", " " }));
        jcbxComboImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbxComboImparesActionPerformed(evt);
            }
        });

        jbtnResultadoParesImpares.setText("RESULTADO");
        jbtnResultadoParesImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultadoParesImparesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbxNumerosDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addComponent(jtxtResultadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcbxComboImpares, 0, 72, Short.MAX_VALUE)
                    .addComponent(jcbxComboPares, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jtxtIngresoParesImpares, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnIngreso)
                    .addComponent(jbtnResultadoParesImpares))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxNumerosDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jcbxComboPares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtIngresoParesImpares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnIngreso))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jcbxComboImpares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnResultadoParesImpares)
                            .addComponent(jtxtResultadoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        sumarCombo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcbxComboImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbxComboImparesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbxComboImparesActionPerformed

    private void jbtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresoActionPerformed
        // TODO add your handling code here:
        ingresoparesImpares();
    }//GEN-LAST:event_jbtnIngresoActionPerformed

    private void jbtnResultadoParesImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultadoParesImparesActionPerformed
        // TODO add your handling code here:
        sumarParesImpares();
    }//GEN-LAST:event_jbtnResultadoParesImparesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jbtnIngreso;
    private javax.swing.JButton jbtnResultadoParesImpares;
    private javax.swing.JComboBox<String> jcbxComboImpares;
    private javax.swing.JComboBox<String> jcbxComboPares;
    private javax.swing.JComboBox<String> jcbxNumerosDefault;
    private javax.swing.JTextField jtxtIngresoParesImpares;
    private javax.swing.JTextField jtxtResultadoCombo;
    // End of variables declaration//GEN-END:variables
}
