/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java1;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabo
 */
public class repaso1 extends javax.swing.JFrame {

    DefaultListModel lista = new DefaultListModel();
    DefaultListModel listaPares = new DefaultListModel();
    DefaultListModel listaImpares = new DefaultListModel();
    DefaultListModel listaMixtos = new DefaultListModel();

    /**
     * Creates new form repaso1
     */
    public repaso1() {
        initComponents();
        llenarLista();
    }

    public void llenarLista() {

        int[] numeros = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};

        for (int i = 1; i <= numeros.length; i++) {

            lista.addElement(i);
        }
        jlstSumaSimple.setModel(lista);
    }

    public void sumarLista1() {

        int resultado = 0;
        int numero;
        for (int i = 0; i < lista.getSize(); i++) {
            numero = (int) lista.getElementAt(i);
            resultado = resultado + numero;
        }

        //JOptionPane.showMessageDialog(rootPane, "EL RESULTADO DE LA LISTA ES: "+resultado);
        jtxtResultadoSimple.setText(String.valueOf(resultado));
    }

    public void ingresoParesImpares() {

        if (Integer.valueOf(jtxtIngresoParesImpares.getText()) % 2 == 0) {
            listaPares.addElement(jtxtIngresoParesImpares.getText());
        } else {
            listaImpares.addElement(jtxtIngresoParesImpares.getText());
        }

        jlstPares.setModel(listaPares);
        jlstImpares.setModel(listaImpares);

    }

    public void resultadoParesImpares() {

        int resultadoPares = 0;
        int numeroPar;
        int resultadoImpares = 0;
        int numeroImpar;

        for (int i = 0; i < listaPares.getSize(); i++) {
            numeroPar = Integer.parseInt(listaPares.getElementAt(i).toString());
            resultadoPares += numeroPar;
        }

        for (int i = 0; i < listaImpares.getSize(); i++) {
            numeroImpar = Integer.parseInt(listaImpares.getElementAt(i).toString());
            resultadoImpares += numeroImpar;
        }

        //jtxtResultadoPares.setText(String.valueOf(resultadoPares));
        //jtxtResultadoImpares.setText(String.valueOf(resultadoImpares));
        listaPares.addElement(resultadoPares);
        listaImpares.addElement(resultadoImpares);
    }

    public void llenarMixtos() {

        listaMixtos.addElement(jtxtIngresoMixtos.getText());
        jtxtIngresoMixtos.setText("");
        jlstMixtos.setModel(listaMixtos);
    }

    public void resultadoMixtos() {

        int numPar;
        int numImpar;
        int resultadoPar=0;
        int resultadoImpar=0;

        for (int i = 0; i < listaMixtos.getSize(); i++) {
            if (Integer.parseInt(listaMixtos.getElementAt(i).toString())%2==0) {
                numPar = Integer.parseInt(listaMixtos.getElementAt(i).toString());
                resultadoPar+=numPar;
            } else {
                  numImpar = Integer.parseInt(listaMixtos.getElementAt(i).toString());
                  resultadoImpar+=numImpar;
            }
        }
        
        JOptionPane.showMessageDialog(null, "RESULTADO PARES: "+resultadoPar+"/n"+"RESULTADO IMPARES:"+resultadoImpar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jlstSumaSimple = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlstPares = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jlstImpares = new javax.swing.JList<>();
        jtxtResultadoPares = new javax.swing.JTextField();
        jbtnIngreso = new javax.swing.JButton();
        jbtnResultado1 = new javax.swing.JButton();
        jbtnSUMA1 = new javax.swing.JButton();
        jtxtResultadoSimple = new javax.swing.JTextField();
        jtxtResultadoImpares = new javax.swing.JTextField();
        jtxtIngresoParesImpares = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jlstMixtos = new javax.swing.JList<>();
        jtxtIngresoMixtos = new javax.swing.JTextField();
        jbtnIngresoMixtos = new javax.swing.JButton();
        jbtnResultadoMixtos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jlstSumaSimple);

        jlstPares.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jlstPares);

        jlstImpares.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jlstImpares);

        jtxtResultadoPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultadoParesActionPerformed(evt);
            }
        });

        jbtnIngreso.setText("INGRESAR");
        jbtnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresoActionPerformed(evt);
            }
        });

        jbtnResultado1.setText("RESULTADO");
        jbtnResultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultado1ActionPerformed(evt);
            }
        });

        jbtnSUMA1.setText("SUMA 1");
        jbtnSUMA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSUMA1ActionPerformed(evt);
            }
        });

        jtxtResultadoImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultadoImparesActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jlstMixtos);

        jbtnIngresoMixtos.setText("INGRESO");
        jbtnIngresoMixtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresoMixtosActionPerformed(evt);
            }
        });

        jbtnResultadoMixtos.setText("RESULTADO");
        jbtnResultadoMixtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResultadoMixtosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnSUMA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtResultadoSimple))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtIngresoParesImpares)
                    .addComponent(jbtnIngreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtResultadoPares, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jtxtResultadoImpares, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnResultado1)))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnIngresoMixtos)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnResultadoMixtos))
                    .addComponent(jtxtIngresoMixtos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtIngresoMixtos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnIngresoMixtos)
                            .addComponent(jbtnResultadoMixtos)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnSUMA1)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtResultadoSimple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtIngresoParesImpares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnIngreso)
                            .addComponent(jbtnResultado1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtResultadoPares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtResultadoImpares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtResultadoParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultadoParesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultadoParesActionPerformed

    private void jtxtResultadoImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultadoImparesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultadoImparesActionPerformed

    private void jbtnSUMA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSUMA1ActionPerformed
        sumarLista1();
    }//GEN-LAST:event_jbtnSUMA1ActionPerformed

    private void jbtnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresoActionPerformed
        // TODO add your handling code here:
        ingresoParesImpares();
        jtxtIngresoParesImpares.setText("");
    }//GEN-LAST:event_jbtnIngresoActionPerformed

    private void jbtnResultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultado1ActionPerformed
        // TODO add your handling code here:
        resultadoParesImpares();
    }//GEN-LAST:event_jbtnResultado1ActionPerformed

    private void jbtnIngresoMixtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresoMixtosActionPerformed
        // TODO add your handling code here:
        llenarMixtos();
    }//GEN-LAST:event_jbtnIngresoMixtosActionPerformed

    private void jbtnResultadoMixtosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResultadoMixtosActionPerformed
        // TODO add your handling code here:
        resultadoMixtos();
    }//GEN-LAST:event_jbtnResultadoMixtosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(repaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(repaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(repaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(repaso1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repaso1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jbtnIngreso;
    private javax.swing.JButton jbtnIngresoMixtos;
    private javax.swing.JButton jbtnResultado1;
    private javax.swing.JButton jbtnResultadoMixtos;
    private javax.swing.JButton jbtnSUMA1;
    private javax.swing.JList<String> jlstImpares;
    private javax.swing.JList<String> jlstMixtos;
    private javax.swing.JList<String> jlstPares;
    private javax.swing.JList<String> jlstSumaSimple;
    private javax.swing.JTextField jtxtIngresoMixtos;
    private javax.swing.JTextField jtxtIngresoParesImpares;
    private javax.swing.JTextField jtxtResultadoImpares;
    private javax.swing.JTextField jtxtResultadoPares;
    private javax.swing.JTextField jtxtResultadoSimple;
    // End of variables declaration//GEN-END:variables
}
